name: Build Calendar

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" 

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.42.1

      - name: Build Calendar
        run: deno run --allow-write --allow-net main.ts

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: calendar-artifacts
          path: build

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: calendar-artifacts

      - name: Configure GitHub Pages
        uses: actions/configure-gh-pages@v3
        with:
          token: ${{ github.token }}
          publish_dir: ./
